name: decor
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # icon
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0

  # state management
  provider: ^6.0.2

  # firebase
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
  flutter_facebook_auth: ^4.1.1

  # web view
  webview_flutter: ^3.0.1

  # shared preferences
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/category/
    - assets/images/pageview/
    - assets/images/success_screen/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Asap
      fonts:
        - asset: assets/fonts/Asap-Regular.ttf

